
services:
  db_test:
    image: postgres:13
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: testdb
      POSTGRES_HOST: db_test
    ports:
      - "5433:5432"
    volumes:
      - db_test_data:/var/lib/postgresql/data
    networks:
      - test_network
    command: ["-c", "log_statement=all"]

  migrate:
    image: migrate/migrate:v4.14.1
    networks:
      - test_network
    volumes:
      - ./migrations:/migrations
    entrypoint: [
      "sh", "-c",
      "until nc -z db_test 5432; do sleep 2; done; migrate -path=/migrations -database postgres://testuser:testpassword@db_test:5432/testdb?sslmode=disable up"
    ]
    depends_on:
      - db_test

  test_app:
    build:
      context: .
      dockerfile: Dockerfile.test
    networks:
      - test_network
    depends_on:
      - db_test
      - migrate
    environment:
      DATABASE_URL: "postgres://testuser:testpassword@db_test:5432/testdb?sslmode=disable"

networks:
  test_network:
    driver: bridge

volumes:
  db_test_data:
